- name: Copiando al etc/network/interfaces
  ansible.builtin.copy:
    src: interfaz_nodo2/interfaces
    dest: /etc/network/
    owner: root
    group: root
    mode: u-rw,g-wx,o-rwx
  notify:
    - reiniciando maquina
